program: code/train.py
method: grid
metric:
  goal: minimize
  name: default 
parameters:
  epochs:
    values: [1000]
  batch-size:
    values: [16]
  lr:
    values: [0.005]
  wd:
    values: [0.0001]
  scheduler-step-size:
    values: [40]
  scheduler-gamma:
    values: [0.8]
  model-type:
    values: ["fno"]
  n-train:
    values: [50]
  n-tests:
    values: [10]
  losses:
    values: ["l2"]
  lam1:
    values: [0.02]
  lam2:
    values: [0.02]
  loading-cond:
    values: ["[0,1]"]
